### ISSUE TITLE
[Tests] Fix Attach error when running all tests at once

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#166] opened 2023-10-11 13:16 UTC
https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/400/allure/#suites/9f9a762740dc93338586150d88864f97/1cda1f2df369eae7/

<img width="1840" alt="Screenshot 2023-10-11 at 16 14 58" src="https://github.com/status-im/desktop-qa-automation/assets/82375995/edc2ce0b-1c9d-4996-915e-7aafe4a2b6c0">

```
aut_id = 'AUT_124140', timeout_sec = 10

    @allure.step('Attaching to "{0}"')
    def attach(aut_id: str, timeout_sec: int = configs.timeouts.PROCESS_TIMEOUT_SEC):
        started_at = time.monotonic()
        _logger.debug(f'Attaching to {aut_id}')
        while True:
            try:
                context = squish.attachToApplication(aut_id)
                _logger.info(f'AUT: {aut_id} attached')
                return context
            except RuntimeError as err:
                _logger.debug(err)
                time.sleep(1)
>           assert time.monotonic() - started_at < timeout_sec, f'Attach error: {aut_id}'
E           AssertionError: Attach error: AUT_124140

driver/context.py:24: AssertionError
```

**Comment by StateOf-Vlado** [comment] 2023-10-18 17:25
Closed as duplicate of https://github.com/status-im/desktop-qa-automation/issues/174

**Closed by StateOf-Vlado** 2023-10-18 17:25 UTC
Labels: CI, UI tests
