### ISSUE TITLE
[EPIC][Wallet][QA] Include watch only per account

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#244] opened 2023-11-01 15:55 UTC
QA for https://github.com/status-im/status-desktop/issues/12305

**Comment by anastasiyaig** [comment] 2023-11-03 06:55
its a dupe of https://github.com/status-im/desktop-qa-automation/issues/182 which i am working on

**Closed by anastasiyaig** 2023-11-03 06:55 UTC
Labels: QA Epic
