### ISSUE TITLE
Keycard regression round (windows is priority)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#443] opened 2024-01-16 11:42 UTC
- retest https://github.com/status-im/status-desktop/issues/11723
- do a regression round for Keycard (10-15 high prio tests)

Use last master for this

Please provide testing results as a link to test rail run (if possible), in case some test cases are missing - would be good to create them as well

NOTE: focus on **Windows** platform, we have a lot of potential issues here

**Comment by anastasiyaig** [comment] 2024-01-18 09:17
@glitchminer please help with this as well

**Comment by anastasiyaig** [comment] 2024-01-18 14:06
feedback from Guy-Louis:

> I tested 0.15.0 with my Mac and completed what’s ok/nok with these scenarios 
> 
> Things that did not work for me 
> Impossible to migrate an account ‘primary or secondary) from desktop to keycard because of a UI issue: it’s impossible to press ‘next’
> Issues while using a card that has no metadata:
> If the status account is using this card, then I can’t generate a new account on the card
> If the status account is using this card, then status doesn’t propose me to add metadata to the card, my card will remain without metadata
> When using an account (let’s say a normal non keycard account) and I want to import a secondary account based on a existing keycard (flow C4): it doesn’t work , it says the card has no metadata and it’s impossible to proceed

Please check on that as well, and cover in TestRail if we dont yet have the coverage

**Comment by lukaszso** [comment] 2024-01-18 14:08
My test run for macOS can be found [here](https://ethstatus.testrail.net/index.php?/runs/view/14456&group_by=cases:section_id&group_order=asc)

**Comment by anastasiyaig** [comment] 2024-01-18 15:31
Related issues:
https://github.com/status-im/status-desktop/issues/13242
https://github.com/status-im/status-desktop/issues/13243

**Comment by anastasiyaig** [comment] 2024-01-23 08:40
@lukaszso could you please provide feedback on how keycard is behaving on windows?
The task is in progress for a long time already. I checked the test run attached and it is 1/3 completed (and on mac)
Please, update test run results and provide necessary info about Windows testing and update task status, thanks

**Comment by lukaszso** [comment] 2024-01-23 09:24
@anastasiyaig current status: 

macOS had an issue with recognizing keycard reader, it was fixed yesterday and i will complete the run for it today.

On Windows there is an issue where i cannot start any flow related to keycard. When consulted with @glitchminer it was discovered that it may be because not all fixes are yet in master.

**Comment by lukaszso** [comment] 2024-01-23 17:36
macOS test run completed. Results can be found [here](https://ethstatus.testrail.net/index.php?/runs/view/14456&group_by=cases:section_id&group_order=asc)

**Comment by lukaszso** [comment] 2024-01-25 00:00
Windows test run completed. Results can be found [here](https://ethstatus.testrail.net/index.php?/runs/view/14523&group_by=cases:section_id&group_order=asc)

List of new issues found:
https://github.com/status-im/status-desktop/issues/13286
https://github.com/status-im/status-desktop/issues/13287
https://github.com/status-im/status-desktop/issues/13288
https://github.com/status-im/status-desktop/issues/13289

**Comment by lukaszso** [comment] 2024-01-25 11:14
Closing as the regression rounds for both macOS and Windows were completed.

**Closed by lukaszso** 2024-01-25 11:14 UTC
Labels: Regression testing
