### ISSUE TITLE
[EPIC][Wallet][QA] Investigate the best way to implement Wallet Connect v2 in Status-Desktop

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#245] opened 2023-11-01 15:56 UTC
QA for https://github.com/status-im/status-desktop/issues/12301

**Comment by anastasiyaig** [comment] 2023-11-03 08:55
duplicate of https://github.com/status-im/desktop-qa-automation/issues/183

**Closed by anastasiyaig** 2023-11-03 08:55 UTC
Labels: QA Epic
